```{css, echo=FALSE}
h1 {
  color: #538135;
  font-family: "Helvetica";
}
h2 {
  color: #538135;
  font-family: "Helvetica";
}
body {
  font-family: "Helvetica";
}
  .nav-pills>li>a:hover, .nav-pills>li>a:focus, .nav-pills>li.active>a,     .nav-pills>li.active>a:hover, .nav-pills>li.active>a:focus{
     background-color: #538135;
     }

```
# Hi there

**I'm James**, I'm a statistician currently working in healthcare analytics and modelling. Before that, I worked in digital marketing but I'm also interested in human factors research, econometrics, polling and urban design.

**You can reach me on:**
[Email](mailto:james_kilgour@outlook.com)  [LinkedIn](https://www.linkedin.com/in/james-kilgour/)   [GitHub](https://github.com/james-kilgour)


## Experience {.tabset .tabset-fade .tabset-pills}

### Statistician/Information Analyst

*Public Health Scotland 2024, Present*

Statistician within LIST, PHS's regional analyst service for primary care clinicians and local councils. Notable projects include:

- Regression modelling to impute patient appointment data. 66% accuracy with McFadden’s pseudo R^2^ = 0.22.

- PCA and clustering analysis on learning disability patients (recently exhibited at the NRS Mental Health Annual Scientific Meeting).

- Forecasting hospital bed capacity using SES models.

- See work GitHub account [here](https://github.com/jamesk-PHS).

### Senior Writer and Analyst

*CopyHouse, 2021-2024*

- Senior staff member responsible for staff training, client onboarding and strategic consultancy.

- Expanded company services to include data analysis on web traffic and search engine ranking performance.

- Client list spanned financial services and technology sectors, including brands like Facebook, Klarna, Blaylock Van, and Tractable.

### Marketing Assistant and Analyst

*Heriot-Watt University Student Union, 2018-2021*

- Introduced, and subsequently led, an annual audit of our social media audience using follower demographic and engagement data.

- Received a Bronze Award in the Marketing Society’s 2020 Star Awards for our organisational rebrand.

## Education {.tabset .tabset-fade .tabset-pills}

### MSc Applied Data Analytics

*University of the Highlands and Islands, Present*

- Studying alongside full-time employment. Data Lab Scholarship recipient. Module specialisms include statistical modelling and geospatial analysis in R.

### BSc Data Science (Applied mathematics and statistics)

*The Open University, Paused*

- Studied alongside full-time employment, achieving a 2:1 in my second year. Modules include linear algebra, calculus, statistics and python programming.

### BSc Psychology

*Heriot-Watt University, Graduated with First Class Honours*

- Awarded both the Brotherton Honours Project Prize and Best Speaker title at a British Psychological Society conference for my dissertation/presentation (respectively) on cognitive factors within political messaging campaigns.

## Skills and Software {.tabset .tabset-fade .tabset-pills}

### Statistics

- Data visualisation (ggplot2, Plotly, Excel)
- Null hypothesis testing & regression analysis
- Point/interval estimation and power analysis
- Time-series analysis and forecasting 
- Multivariate analysis and clustering
- Information governance, GDPR & statistical disclosure control.

### Programming and Software

- R, tidyverse 
- Markdown/Bookdown, Flexdashboard, Shiny, Excel
- SQL, HTML, CSS, Git/GitHub
- Office 365, Google Workspace
- Trello, ClickUp, Planner

### General

- Project management within agency environments
- Finance/procurement and budget optimisation
- Customer/stakeholder engagement and communication
- Line management and leadership experience

## Data viz examples

Coming soon 👀
